### PR TITLE
amend pseudo-version of two packages

### PR DESCRIPTION
**Pull request by suifengtec**
`make serve` throw an error :

```bash

λ make serve
./preparetranslations.sh
Preparing merged file for common side.. (main)
go: flamingo.me/flamingo/v3@v3.0.3 requires
        github.com/Ompluscator/oauth2@v0.0.0-20190101010101-b7626857: invalid pseudo-version: revision is shorter than canonical (b76268579942)
Makefile:32: recipe for target 'translation' failed
make: *** [translation] Error 1

```

I try to modify the `go.mod`:

```bash
b7626857 -> b76268579942

```

try again, it throw another error:

```bash

λ make serve
./preparetranslations.sh
Preparing merged file for common side.. (main)
go: flamingo.me/flamingo/v3@v3.0.3 requires
        github.com/Ompluscator/oauth2@v0.0.0-20190101010101-b76268579942: invalid pseudo-version: does not match version-control timestamp (2019-01-21T14:11:51Z)
Makefile:32: recipe for target 'translation' failed
make: *** [translation] Error 1

```

I try to modify the `go.mod`:

```bash
20190101010101 -> 20190121141151

```

try again, it throw another error again:

```bash

λ make serve
./preparetranslations.sh
Preparing merged file for common side.. (main)
go: flamingo.me/pugtemplate@v1.0.0 requires
        github.com/thebod/otto@v0.0.0-20180101010101-83d297c4b64aeb2de4268d9a54c9a503ae2d8139: invalid pseudo-version: revision is longer than canonical (83d297c4b64a)
Makefile:32: recipe for target 'translation' failed
make: *** [translation] Error 1

```

I try to modify the `go.mod`:

```bash
83d297c4b64aeb2de4268d9a54c9a503ae2d8139 -> 83d297c4b64a

```

try again, it throw another error again:

```bash

λ make serve
./preparetranslations.sh
Preparing merged file for common side.. (main)
go: flamingo.me/pugtemplate@v1.0.0 requires
        github.com/thebod/otto@v0.0.0-20180101010101-83d297c4b64a: invalid pseudo-version: does not match version-control timestamp (2017-07-12T09:19:32Z)

Makefile:32: recipe for target 'translation' failed
make: *** [translation] Error 1

```

I try to modify the `go.mod`:

```bash
20180101010101 -> 20170712091932

```

try again...it works fine!

### CODE REVIEW

**Comment by suifengtec** [comment]
@danielpoe  

I use go 1.13.5

**Comment by danielpoe** [comment]
Ok thanks - I merged your PullRequest and also removed the override for github.com/robertkrimen/otto

It works now for you still?

**Comment by suifengtec** [comment]
@danielpoe it works fine!

**Comment by danielpoe** [comment]
Perfect thanks

Let me know if there are further issues we can assist with

Cheers

**Pull request merged**
